baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'LoRes Mesh'
theme = 'lores'


[menus]
[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Docs'
pageRef = '/docs'
weight = 20

[module]
[module.hugoVersion]
extended = false
min = '0.146.0'
